

basic-analysis:
	python sfr_to_rate_nobins.py --starmetal-file ~/PersonalJBArchive/boring-galaxy/z0.016.starmetal.dat > basic-boring.dat &
	python sfr_to_rate_nobins.py --starmetal-file ~/PersonalJBArchive/exciting-galaxy/z0.016.starmetal.dat > basic-exciting.dat &


bundle:
	tar cvzf richard-results-bundle.tgz bh_bh/ bh_ns/ ns_ns
