

basic-analysis:
	python sfr_to_rate_nobins.py --starmetal-file ~/PersonalJBArchive/boring-galaxy/z0.016.starmetal.dat > basic-boring.dat &
	python sfr_to_rate_nobins.py --starmetal-file ~/PersonalJBArchive/exciting-galaxy/z0.016.starmetal.dat > basic-exciting.dat &


full-analysis:
	mkdir bh-bh_exciting; cb
